Numpy Arrays

In [8]:
#import numpy library
import numpy as np

In [10]:
x = np.array([45,67,57,60])
print(x)
print(type(x))
print(x.dtype)

[45 67 57 60]
<class 'numpy.ndarray'>
int32


In [12]:
x = np.array([45,67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

[45.  67.  57.   9.8]
<class 'numpy.ndarray'>
float64


In [14]:
x = np.array(["A",67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '57' '9.8']
<class 'numpy.ndarray'>
<U32


In [16]:
a2 = np.array([[20,23],[39,42]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 23]
 [39 42]]
<class 'numpy.ndarray'>
(2, 2)


In [20]:
#Reshaping an array
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [22]:
# create an array with arange
c = np.arange(34,59)
print(c)
type(c)

[34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


numpy.ndarray

In [28]:
# use of around
d = np.array([1.3456, 3.10987,4.91236])
print(d)
np.around(d,2)

[1.3456  3.10987 4.91236]


array([1.35, 3.11, 4.91])

In [39]:
#use of np.sqrt()
a = np.array([1.3456, 3.10987,4.91236])
print(a)
print(np.around(np.sqrt(a),2))

[1.3456  3.10987 4.91236]
[1.16 1.76 2.22]


In [43]:
a1 = np.array([[3,4,5,8],[7,2,8,np.NAN]])
print(a1)
print(a1.dtype)
print(a1.shape)

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]
float64
(2, 4)


In [ ]:
a1 = np.array([[3,4,5,8],[7,2,8,np.NAN]])
print(a1)
print(a1.dtype)
print(a1.shape)

In [47]:
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [49]:
a2 = np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [51]:
a2 = np.array([[3,4,6],[7,9,10],[4,6,12]])
print(a2)
a3 = np.sum(a1,axis = 1)
a3 = np.sum(a2,axis = 0)
print(a3)

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[14 19 28]


In [55]:
print(a2)
print(np.mean(a2,axis = 0))
print(np.mean(a2,axis = 1))

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[4.66666667 6.33333333 9.33333333]
[4.33333333 8.66666667 7.33333333]


In [57]:
a5 = np.array([[3,4,5],[7,2,10],[4,9,12]])
print(a5)
np.fill_diagonal(a5,0)
print(a5)

[[ 3  4  5]
 [ 7  2 10]
 [ 4  9 12]]
[[ 0  4  5]
 [ 7  0 10]
 [ 4  9  0]]


In [59]:
A = np.array([[20,23],[39,42]])
B = np.array([[34,59],[89,81]])
c = np.matmul(A,B)
print(c)

[[2727 3043]
 [5064 5703]]


In [61]:
print(A.T)
print(B.T)

[[20 39]
 [23 42]]
[[34 89]
 [59 81]]


In [65]:
a5 = np.array([[3,4,5],[7,2,10],[4,9,12]])
a5

array([[ 3,  4,  5],
       [ 7,  2, 10],
       [ 4,  9, 12]])

In [67]:
a5[1][1]

2

In [71]:
a5[2][2]

12

In [73]:
a5[1:2,0:2]

array([[7, 2]])